spring.application.name=hibernate-practical

spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=4c6a20d0b9f9e8a0965f0006e7588b75eab44c8af06c0bc009ba528d9ce0da32
jwt.expiration=3600000